export const END_DISABLED = 'END_DISABLED'
export const TREND_MOVE_CONTENT = 'TREND_MOVE_CONTENT'
export const START_DISABLED = 'START_DISABLED'
export const TREND_BACK_CONTENT = 'TREND_BACK_CONTENT'
